### ISSUE TITLE
Broken, calls old version of API

### ISSUE THREAD

**Issue by matthewdeanmartin** [marinko-peso/haveibeenpwned#6]
'This version of the API has been discontinued, please use V3: https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/'

I'll see if I can make an PR if someone else doesn't do it first.

Ah, it is now a paid API because of abuse of the free API. Fixing this will cost $3.50 a month and then using it will also cost users $3.50 a month.

https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/

**Comment by marinko-peso** [comment]
@matthewdeanmartin I am currently not great on time to work on this so feel free to put up a PR and will gladly merge it. Will add a mention in the README about this issue for potential users.
Thanks for your help and for this insight!
